default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL_ACTION_CABLE") { "redis://localhost:6379/1" } %>


development:
  <<: *default
  channel_prefix: currency_rate_development

test:
  adapter: test
  channel_prefix: currency_rate_test

production:
  <<: *default
  channel_prefix: currency_rate_production
